config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "blogs#index"
  resources :blogs, only:[:new, :create, :index, :show, :destroy] do
    resources :comments, only:[:create, :destroy]
    resources :favorites, only:[:create, :destroy]
  end
  resources :users, only:[:show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

  belongs_to :user
  attachment :image
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :blog
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :blogs, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    blogs_path
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!,except: [:index, :show]

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    if @blog.save
      redirect_to blogs_path
    else
      render :new
    end
  end

  def index
    @blogs = Blog.page(params[:page]).reverse_order
  end

  def show
    @blog = Blog.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path
  end

  private


  def blog_params
    params.require(:blog).permit(:title, :image, :body)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    blog = Blog.find(params[:blog_id])
    comment = current_user.comments.new(comment_params)
    comment.blog_id = blog.id
    comment.save
    redirect_to blog_path(blog)
  end

  def destroy
    Comment.find_by(id:params[:id], blog_id:params[:blog_id]).destroy
    redirect_to blog_path(params[:blog_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    blog = Blog.find(params[:blog_id])
    favorite = current_user.favorites.new(blog_id: blog.id)
    favorite.save
    redirect_to blog_path(blog)
  end

  def destroy
    blog = Blog.find(params[:blog_id])
    favorite = current_user.favorites.find_by(blog_id: blog.id)
    favorite.destroy
    redirect_to blog_path(blog)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @user = User.find(params[:id])
    @blogs = @user.blogs.page(params[:page]).reverse_order
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_list.html.erb
<div class="container py-5">
  <% blogs.each do |blog| %>
    <div class="card mx-auto mt-4 shadow-lg" style="max-width: 500px">
      <%= link_to blog_path(blog.id) do %>
        <%= attachment_image_tag blog, :image, fallback: "no_image.jpeg",class:"card-img-top" %>
      <% end %>
      <div class="card-body">
        <div class="row">
          <div class="col-2">
            <%= attachment_image_tag blog.user, :profile_image,  size: "50x50", fallback: "logo.jpeg", class:"mt-2 rounded-circle" %>
          </div>
          <div class="col-10">
            <h4 class="card-title">
              <%= link_to blog_path(blog.id) do %>
                <%= blog.title %>
              <% end %>
            </h4>
            <p class="card-text">
              <%= blog.user.name %> | <%= blog.comments.count %> コメント
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%= paginate blogs %>
</div>

app/views/blogs/index.html.erb
<%= render 'blogs/list', blogs: @blogs %>

app/views/blogs/new.html.erb
<div class="container py-3">
  <h1><i class="fas fa-pencil-alt"></i> 投稿フォーム</h1>
  <% if @blog.errors.any? %>
    <%= @blog.errors.count %>件のエラーが発生しました
    <% @blog.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
  <%= form_with model: @blog, local:true do |f| %>
    <table class="table table-borderless">
      <tr>
        <td>画像</td>
        <td><%= f.attachment_field :image %></td>
      </tr>
      <tr>
        <td>タイトル</td>
        <td><%= f.text_field :title %></td>
      </tr>
      <tr>
        <td>本文</td>
        <td><%= f.text_area :body %></td>
      </tr>
      <tr>
        <td></td>
        <td><%= f.submit '投稿' %></td>
      </tr>
    </table>
  <% end %>
</div>

app/views/blogs/show.html.erb
<div class="container py-5">
  <div class="card mx-auto mt-4 shadow-lg" style="max-width: 800px">
    <%= attachment_image_tag @blog, :image, fallback: "no_image.jpeg",class:"card-img-top" %>
    <div class="card-body">
      <div class="row">
        <div class="col-1">
          <%= attachment_image_tag @blog.user, :profile_image,  size: "50x50", fallback: "logo.jpeg", class:"mt-2 rounded-circle" %>
        </div>
        <div class="col-11">
          <h4 class="card-title">
            <%= @blog.title %>
          </h4>
          <p class="card-text">
            <%= @blog.body %>
          </p>
          <p class="card-user">
            <%= @blog.user.name %> | <%= @blog.created_at.strftime('%Y/%m/%d') %> |
            <% if @blog.favorited_by?(current_user) %>
                <%= link_to blog_favorite_path(@blog), method: :delete do %>
                  ♥<%= @blog.favorites.count %> いいね
                <% end %>
              <% else %>
                <%= link_to blog_favorites_path(@blog), method: :post do %>
                  ♡<%= @blog.favorites.count %> いいね
                <% end %>
            <% end %>
            <% if @blog.user == current_user %>
              | <%= link_to "削除", blog_path(@blog), method: :delete %>
            <% end %>
          </p>
        </div>
      </div>
    </div>
    <div class="card-body">
      <div class="row blog-comments">
        <p>コメント件数:<%= @blog.comments.count %></p>
        <table class="table table-borderless">
          <% @blog.comments.each do |comment| %>
            <tr>
              <td><%= comment.user.name %></td>
              <td><%= comment.comment %></td>
              <td><%= comment.created_at.strftime('%Y/%m/%d') %></td>
              <td>
                <% if comment.user == current_user %>
                  <%= link_to "削除", blog_comment_path(comment.blog, comment), method: :delete %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
      <div class="new-comment">
        <%= form_with(model:[@blog, @comment], local: true) do |f| %>
          <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
          <%= f.submit "送信する" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Web</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-light" style="background-color: #e3f2fd">
        <div class="container">
          <div class="navbar-brand p-3">
            <%= link_to root_path, class:"text-dark" do %>
              <i class="fas fa-book"></i> Blogger's
            <% end %>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item active">
                  <%= link_to new_blog_path, class:"nav-link text-dark" do %>
                    <i class="fas fa-pencil-alt"></i> 投稿フォーム
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to user_path(current_user.id), class:"nav-link text-dark" do %>
                    <i class="far fa-address-book"></i> マイページ
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-dark" do %>
                    <i class="fas fa-sign-out-alt"></i> ログアウト
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to new_user_registration_path, class:"nav-link text-dark" do %>
                    <i class="fas fa-user-plus"></i> 新規登録
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_session_path, class:"nav-link text-dark" do %>
                    <i class="fas fa-sign-in-alt"></i> ログイン
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <%= yield %>
    </main>
    <footer class="pt-5 pb-4", style="background-color: #e3f2fd">
      <div class="container">
        <div class="row">
            あなたの日々を語る場所...</br>
            Blogger's
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container py-3">
  <h2>プロフィール編集</h2>
  <%= form_with model:@user, local:true do |f| %>
    <table class="table table-borderless">
      <tr>
        <td>名前</td>
        <td><%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%></td>
      </tr>
      <tr>
        <td>プロフィール画像</td>
        <td><%= attachment_image_tag @user, :profile_image, size: "100x100", fallback: "logo.jpg"%></td>
        <td><%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %></td>
      </tr>
      <tr>
        <td></td>
        <td><%= f.submit "変更を保存" %></td>
      </tr>
    </table>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container py-3">
  <div class="row ml-5 mt-4">
    <div class="col-2">
      <%= attachment_image_tag @user, :profile_image, size: "50x50", fallback: "logo.jpeg" %>
    </div>
    <div class="col-10">
      <h3 class="profile-name"><%= @user.name %></h3>
      <% if @user.id == current_user.id %>
        <%= link_to "プロフィール編集", edit_user_path(@user), class:"btn btn-outline-primary" %>
      <% end %>
    </div>
  </div>
</div>
<%= render 'blogs/list', blogs: @blogs %>